import dotenv from "dotenv";
dotenv.config();

const PORT = process.env.PORT || 5001;
const NODE_ENV = process.env.NODE_ENV;
const JWT_SECRET = process.env.JWT_SECRET;
const POSTGRESQL_HOST = process.env.POSTGRESQL_HOST;
const POSTGRESQL_PORT = process.env.POSTGRESQL_PORT;
const POSTGRESQL_USERNAME = process.env.POSTGRESQL_USERNAME;
const POSTGRESQL_DATABASE = process.env.POSTGRESQL_DATABASE;
const POSTGRESQL_PASSWORD = process.env.POSTGRESQL_PASSWORD;
const MESSAGE_BROKER_URL = process.env.MESSAGE_BROKER_URL;
const EXCHANGE_NAME = process.env.EXCHANGE_NAME;
const AUTH_SERVICE_BINDING_KEY = process.env.AUTH_SERVICE_BINDING_KEY;
const AUTH_SERVICE_RPC = process.env.AUTH_SERVICE_RPC;
const PROFILE_SERVICE_BINDING_KEY = process.env.PROFILE_SERVICE_BINDING_KEY;
const PROFILE_SERVICE_RPC = process.env.PROFILE_SERVICE_RPC

export {
  PORT,
  NODE_ENV,
  JWT_SECRET,
  POSTGRESQL_HOST,
  POSTGRESQL_USERNAME,
  POSTGRESQL_DATABASE,
  POSTGRESQL_PASSWORD,
  POSTGRESQL_PORT,
  MESSAGE_BROKER_URL,
  EXCHANGE_NAME,
  AUTH_SERVICE_BINDING_KEY,
  AUTH_SERVICE_RPC,
  PROFILE_SERVICE_BINDING_KEY,
  PROFILE_SERVICE_RPC
};
